// This file is auto-generated by scripts/generate-pack-index.ts.
// Do not edit manually. Add pack JSON files to src/data/packs/ instead.

import pack000 from './pack_000_introduction_to_mandarin.json';
import pack001 from './pack_001_i_you_to_be_have.json';
import pack002 from './pack_002_daily_actions.json';
import pack003 from './pack_003_question_building.json';
import pack004 from './pack_004_time_routine.json';
import pack005 from './pack_005_location_movement.json';
import pack006 from './pack_006_eating_buying.json';
import pack007 from './pack_007_people_family.json';
import pack008 from './pack_008_describing_things.json';
import pack009 from './pack_009_basic_opinions.json';
import pack010 from './pack_010_numbers_0_10.json';
import pack011 from './pack_011_numbers_11_100.json';
import pack012 from './pack_012_days_weeks_months.json';
import pack013 from './pack_013_basic_measure_words.json';
import pack014 from './pack_014_this_that_which.json';
import pack015 from './pack_015_food_expansion.json';
import pack016 from './pack_016_drinks_ordering.json';
import pack017 from './pack_017_transport_basics.json';
import pack018 from './pack_018_directions.json';
import pack019 from './pack_019_simple_past_le.json';
import pack020 from './pack_020_ability_hui_neng.json';
import pack021 from './pack_021_weather.json';
import pack022 from './pack_022_clothes.json';
import pack023 from './pack_023_colors.json';
import pack024 from './pack_024_body_health.json';
import pack025 from './pack_025_work_study.json';
import pack026 from './pack_026_hobbies.json';
import pack027 from './pack_027_feelings.json';
import pack028 from './pack_028_common_places.json';
import pack029 from './pack_029_at_restaurant.json';
import pack030 from './pack_030_at_shop.json';
import pack031 from './pack_031_asking_for_help.json';
import pack032 from './pack_032_making_plans.json';

export const rawContentPacks = [
  pack000,
  pack001,
  pack002,
  pack003,
  pack004,
  pack005,
  pack006,
  pack007,
  pack008,
  pack009,
  pack010,
  pack011,
  pack012,
  pack013,
  pack014,
  pack015,
  pack016,
  pack017,
  pack018,
  pack019,
  pack020,
  pack021,
  pack022,
  pack023,
  pack024,
  pack025,
  pack026,
  pack027,
  pack028,
  pack029,
  pack030,
  pack031,
  pack032,
] as unknown[];
