import { readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDir, '..');
const packsDir = path.join(projectRoot, 'src', 'data', 'packs');
const outputPath = path.join(packsDir, 'index.ts');
const packFilePattern = /^pack_(\d+).*\.json$/;

function packOrder(fileName: string) {
  const match = fileName.match(packFilePattern);
  return match ? Number(match[1]) : Number.MAX_SAFE_INTEGER;
}

function importName(fileName: string, index: number) {
  const prefix = fileName.match(packFilePattern)?.[1] ?? String(index).padStart(3, '0');
  return `pack${prefix}`;
}

async function generatePackIndex() {
  const files = (await readdir(packsDir))
    .filter((file) => packFilePattern.test(file))
    .sort((a, b) => packOrder(a) - packOrder(b) || a.localeCompare(b));

  const imports = files.map((file, index) => `import ${importName(file, index)} from './${file}';`);
  const packNames = files.map(importName);
  const arrayItems = packNames.map((name) => `  ${name},`);

  const content = [
    '// This file is auto-generated by scripts/generate-pack-index.ts.',
    '// Do not edit manually. Add pack JSON files to src/data/packs/ instead.',
    '',
    ...imports,
    '',
    'export const rawContentPacks = [',
    ...arrayItems,
    '] as unknown[];',
    '',
  ].join('\n');

  await writeFile(outputPath, content, 'utf8');
  console.log(`Generated ${path.relative(projectRoot, outputPath)} with ${files.length} packs`);
}

generatePackIndex().catch((error) => {
  console.error(error);
  process.exit(1);
});
